include:
  - project: 'geniussports/engage/f2p/common-gitlab-ci-templates'
    ref: 'main'
    file: 'frontend/templates/standard-workflow.yml'
  - project: 'geniussports/engage/f2p/common-gitlab-ci-templates'
    ref: 'main'
    file: 'frontend/templates/jobs.yml'

stages:
  - build
  - deploy

Build:
  stage: build
  extends:
    - .install-packages-before
    - .keep-build-artifacts
  script:
    - echo "Start build of ${ENV_NAME} ${PROJECT_NAME} to ${SITE_URL}";
    - node tools/choose_app.mjs -p $PROJECT_NAME
    - !reference [.tasks, build]
    - !reference [.tasks, optimize-images]
  interruptible: true
  tags:
    - gsm-medium-large-memory

##################
### Deploy Job ###
##################

Deploy:
  stage: deploy
  environment:
    name: $ENV_NAME
    url: $SITE_URL
  extends:
    - .deploy-job